/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FlipRandomInterface extends Interface {
  getFunction(nameOrSignature: "flipCoin"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "flip"): EventFragment;

  encodeFunctionData(functionFragment: "flipCoin", values?: undefined): string;

  decodeFunctionResult(functionFragment: "flipCoin", data: BytesLike): Result;
}

export namespace flipEvent {
  export type InputTuple = [arg0: AddressLike, arg1: boolean];
  export type OutputTuple = [arg0: string, arg1: boolean];
  export interface OutputObject {
    arg0: string;
    arg1: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlipRandom extends BaseContract {
  connect(runner?: ContractRunner | null): FlipRandom;
  waitForDeployment(): Promise<this>;

  interface: FlipRandomInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  flipCoin: TypedContractMethod<[], [boolean], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "flipCoin"
  ): TypedContractMethod<[], [boolean], "nonpayable">;

  getEvent(
    key: "flip"
  ): TypedContractEvent<
    flipEvent.InputTuple,
    flipEvent.OutputTuple,
    flipEvent.OutputObject
  >;

  filters: {
    "flip(address,bool)": TypedContractEvent<
      flipEvent.InputTuple,
      flipEvent.OutputTuple,
      flipEvent.OutputObject
    >;
    flip: TypedContractEvent<
      flipEvent.InputTuple,
      flipEvent.OutputTuple,
      flipEvent.OutputObject
    >;
  };
}
